// Assemble the Shopify theme in shopify/theme and zip it for upload.
//
//   npm run shopify:build
//
// - assets/theme.css  = src/styles/global.css + the component styles from the
//                       Astro site + shopify/src/shopify.css (one design source)
// - assets/*.woff2    = self-hosted fonts from Fontsource
// - snippets/logo-*   = brand SVGs from src/assets/brand
// - assets/*.jpg      = default campaign imagery (used until you upload your own
//                       images in the theme editor)
// - shopify/lane-change-theme.zip — upload in Shopify admin → Online Store → Themes
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const THEME = join(ROOT, 'shopify/theme');
const r = (p) => readFileSync(join(ROOT, p), 'utf8');

/* ---------- theme.css ---------- */
const componentFiles = [
  'src/components/Header.astro',
  'src/components/Footer.astro',
  'src/components/CartDrawer.astro',
  'src/components/SearchOverlay.astro',
  'src/components/ProductCard.astro',
  'src/components/Listing.astro',
  'src/components/home/Hero.astro',
  'src/components/home/CategoryStrip.astro',
  'src/components/home/FeaturedCollection.astro',
  'src/components/home/BrandStatement.astro',
  'src/layouts/Base.astro',
  'src/pages/products/[slug].astro',
  'src/pages/collections/index.astro',
  'src/pages/collections/[slug].astro',
  'src/pages/cart.astro',
  'src/pages/about.astro',
  'src/pages/journal/index.astro',
  'src/pages/journal/[slug].astro',
  'src/pages/contact.astro',
  'src/pages/account.astro',
  'src/pages/search.astro',
  'src/pages/404.astro',
];
const unscope = (css) => css.replace(/:global\(([^()]*(?:\([^()]*\))?[^()]*)\)/g, '$1');
let css = `/* LANE CHANGE — generated by tools/build_shopify_theme.mjs. Edit the sources, not this file. */\n\n`;
css += r('src/styles/global.css');
for (const f of componentFiles) {
  const src = r(f);
  const blocks = [...src.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map((m) => m[1]);
  if (blocks.length) css += `\n\n/* ---- ${f} ---- */\n${blocks.map(unscope).join('\n')}`;
}
css += `\n\n/* ---- shopify/src/shopify.css ---- */\n${r('shopify/src/shopify.css')}`;
writeFileSync(join(THEME, 'assets/theme.css'), css);

/* ---------- fonts ---------- */
const fonts = [
  ['barlow-condensed', 'barlow-condensed-latin-500-normal.woff2'],
  ['barlow-condensed', 'barlow-condensed-latin-600-normal.woff2'],
  ['ibm-plex-mono', 'ibm-plex-mono-latin-400-normal.woff2'],
  ['ibm-plex-mono', 'ibm-plex-mono-latin-500-normal.woff2'],
  ['cormorant-garamond', 'cormorant-garamond-latin-500-normal.woff2'],
];
for (const [pkg, file] of fonts) {
  copyFileSync(join(ROOT, 'node_modules/@fontsource', pkg, 'files', file), join(THEME, 'assets', file));
}

/* ---------- brand marks → snippets ---------- */
const brand = [
  ['wordmark', 'logo-wordmark', 'brand-wordmark', 'Lane Change'],
  ['monogram', 'logo-monogram', 'brand-monogram', 'LC'],
  ['star', 'logo-star', 'brand-star', ''],
];
for (const [svg, snippet, cls] of brand) {
  const markup = r(`src/assets/brand/${svg}.svg`)
    .trim()
    .replace('<svg ', `<svg class="${cls} {{ class }}" aria-hidden="true" focusable="false" `);
  writeFileSync(
    join(THEME, 'snippets', `${snippet}.liquid`),
    `{%- comment -%} Generated from src/assets/brand/${svg}.svg — usage: {% render '${snippet}', class: '…' %} {%- endcomment -%}\n${markup}\n`,
  );
}

/* ---------- default imagery ---------- */
const images = [
  ['hero-campaign', 2000],
  ['hero-campaign-mobile', 1000],
  ['category-tees', 1400],
  ['category-hoodies', 1400],
  ['category-story', 1600],
  ['brand-statement', 2000],
];
for (const [name, width] of images) {
  await sharp(join(ROOT, 'src/assets/images', `${name}.jpg`))
    .resize({ width, withoutEnlargement: true })
    .jpeg({ quality: 82, progressive: true, mozjpeg: true })
    .toFile(join(THEME, 'assets', `${name}.jpg`));
}
copyFileSync(join(ROOT, 'public/favicon.svg'), join(THEME, 'assets/favicon.svg'));

/* ---------- zip ---------- */
const zip = join(ROOT, 'shopify/lane-change-theme.zip');
if (existsSync(zip)) rmSync(zip);
execFileSync('zip', ['-r', '-q', '-X', zip, 'assets', 'config', 'layout', 'locales', 'sections', 'snippets', 'templates'], { cwd: THEME });
console.log(`theme.css ${(css.length / 1024).toFixed(0)} KB · zip → shopify/lane-change-theme.zip`);
